import dotenv from "dotenv";
import express from "express";
import {createServer} from "node:http";
import cors from "cors";
import mongoose from "mongoose";
import path from "node:path";
import {fileURLToPath} from "url";
import {Server} from "socket.io";
import {randomUUID} from "node:crypto";

import playerRouter from "./Routes/playerRoute.js";
import gameStateRouter from "./Routes/gameStateRoute.js";
import gameRoomRouter from "./Routes/gameRoomRoute.js";
import gameConfigurationRouter from "./Routes/gameConfigurationRoute.js";
import {Console} from "node:console";

// Configure env variables
dotenv.config();

const app = express(); // make an express app

const expressServer = createServer(app);
/* This line creates an HTTP server using the createServer method from the http module, with app (an Express application instance) as the request handler.
It essentially sets up an HTTP server that uses the Express application to handle incoming requests. */

const port = process.env.PORT || 5000; //this is for just for deployment (the backend hosting platform will assign us a random port number)
expressServer.listen(port, () => {
	console.log(`HTTP Server running on port ${port}`);
});

const io = new Server(expressServer, {
	cors: {
		origin: "*",
		methods: ["GET", "POST"],
	},
	connectionStateRecovery: {},
}); /* This line creates a new instance of a Socket.IO Server (io) that is attached to the previously created HTTP server (expressServer).
The configuration object passed to the Server constructor sets up Cross-Origin Resource Sharing (CORS) to allow requests from any origin (origin: "*") and to permit only GET and POST methods.*/

const uri = process.env.ATLAS_URI;

app.get("/", (req, res) => {
	res.send("You have reached the card game API...");
});

let onlineUsers = {};
let lastMovePlayedInRoom = {};
let pileOfCardsInEachRoom = {};

/* ------------------------------------------------------------------ */
/* ROOM METADATA + RECONNECTION STATE                                  */
/* ------------------------------------------------------------------ */
/*
	A socket id dies with the connection, so it cannot be an identity.
	Every player carries a `playerId` (generated by the client, kept in
	sessionStorage) which is what we match on when somebody comes back.
	Everything else that used to live implicitly in the socket id - whose
	turn it is, who played last, how much time is on the clock - is kept
	here so a returning player can be handed the game exactly as they left it.
*/
const roomMeta = new Map(); // roomCode -> {gameStarted, currentTurnSocketID, lastPlayedSocketID, isNewTurn}
const pendingRemovals = new Map(); // playerId -> timeoutId

// Overridable so the grace window can be shortened in tests.
const RECONNECT_GRACE_SECONDS = Number(process.env.RECONNECT_GRACE_SECONDS) || 60;
const MAX_PLAYERS_PER_ROOM = 4;

const getRoomMeta = (roomCode) => {
	if (!roomMeta.has(roomCode)) {
		roomMeta.set(roomCode, {gameStarted: false, currentTurnSocketID: null, lastPlayedSocketID: null, currentCardValue: null, isNewTurn: false});
	}
	return roomMeta.get(roomCode);
};

const playersInRoom = (roomCode) => onlineUsers[roomCode] ?? [];
// A seat held open for somebody who dropped is not a seat quick match can sell.
const seatedCount = (roomCode) => playersInRoom(roomCode).filter((player) => player.connected !== false).length;
const everyoneIsConnected = (roomCode) => playersInRoom(roomCode).every((player) => player.connected !== false);

/*
	A player who is gone for good is not deleted from the room: the hand in
	front of their chair is still in play. The seat is marked
	`awaitingReplacement` instead, and the room sits frozen until somebody -
	the original player, or a newcomer - sits down in it.
*/
const openSeatsInRoom = (roomCode) => playersInRoom(roomCode).filter((player) => player.awaitingReplacement);
const openSeatSummary = (roomCode) => openSeatsInRoom(roomCode).map(({playerId, name}) => ({playerId, name}));

// What a joiner can be sold: a vacated chair mid game, a free slot in a lobby.
const freeSeatCount = (roomCode) => {
	if (roomMeta.get(roomCode)?.gameStarted) return openSeatsInRoom(roomCode).length;
	return MAX_PLAYERS_PER_ROOM - playersInRoom(roomCode).length;
};

// Nothing may advance the turn while a chair is empty, or the game would deal
// itself into a seat nobody is sitting in.
const roomIsPaused = (roomCode) => !everyoneIsConnected(roomCode);

const cancelPendingRemoval = (playerId) => {
	if (!pendingRemovals.has(playerId)) return;
	clearTimeout(pendingRemovals.get(playerId));
	pendingRemovals.delete(playerId);
};
//LETS TALK FOR A SECOND
/*
 I NEED TO STORE ONLINEUSERS IN A DICTIONNARY TYPE DATA DTRUCT WHERE THE KEY IS THE ROOMCODE AND THE VALUE IS AN ARRAY OF THE PLAYER OBJECTS THAT ARE IN THE ROOM
*/

// Add these helper functions above your socket.io connection handler
const createDeck = () => {
	const suits = ["C", "D", "H", "S"];
	const values = ["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"];
	const deck = [];

	//1 deck is used here
	//if at a later point more decks area added , should make sure every card is unique
	//to avoid dnd-kit issues , also make sure that deck.slice is updated from 13 to 13 * number_of_decks_used
	const number_of_decks_used = 1;
	for (let index = 0; index < number_of_decks_used; index++) {
		for (let suit of suits) {
			for (let value of values) {
				deck.push(`${value}${suit}`);
			}
		}
	}
	deck.push("1J", "2J"); // Add the jokers
	return deck;
};

const isJoker = (card) => card === "1J" || card === "2J";
const cardMatchesClaim = (card, claimedValue) => isJoker(card) || card.slice(0, -1) === claimedValue;

const shuffleDeck = (deck) => {
	for (let i = deck.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[deck[i], deck[j]] = [deck[j], deck[i]];
	}
	return deck;
};

const assignNewLeader = (roomCode) => {
	if (!onlineUsers[roomCode] || onlineUsers[roomCode].length === 0) return;

	const hasLeader = onlineUsers[roomCode].some((player) => player.isLeader);

	if (!hasLeader && onlineUsers[roomCode].length > 0) {
		onlineUsers[roomCode][0].isLeader = true;
		// Notify the new leader
		io.to(onlineUsers[roomCode][0].socketID).emit("updateLocalPlayer", onlineUsers[roomCode][0]);
		// Notify all players in the room about the updated user list
		io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
	}
};

/**
 *
 *
 */
const findNextTurn = (socketID, roomCode) => {
	//could be interrupted by accuse action in that case : 2 cases arise :
	//if accuser is right the turn goes to the accuser
	//if accuser is wrong the turn goes to the accused
	//need a way to store the accused and the accuser
	//also need to find a way to get the actiontype so it can be displayed in events section
	//circular motion of turns thanks to moudlo operator
	const currentPlayerIndex = onlineUsers[roomCode]?.findIndex((player) => player.socketID === socketID);
	const nextPlayerIndex = (currentPlayerIndex + 1) % onlineUsers[roomCode]?.length;
	return onlineUsers[roomCode][nextPlayerIndex];
};

// Add at the top with other global variables
const TURN_DURATION = 30; // Duration of each turn in seconds
const roomTimers = new Map(); // Store timer intervals for each room
const chatHistory = new Map(); // Store chat history for each room

/* ------------------------------------------------------------------ */
/* TURN TIMER                                                          */
/* ------------------------------------------------------------------ */
/*
	The clock is pausable: while anybody in the room is mid-reconnect the
	turn must not tick down, otherwise a player loses their turn to a
	network blip they had no way to react to.
*/
const clearRoomTimer = (roomCode) => {
	const timer = roomTimers.get(roomCode);
	if (timer?.intervalId) clearInterval(timer.intervalId);
	roomTimers.delete(roomCode);
};

const runRoomTimer = (roomCode) => {
	const timer = roomTimers.get(roomCode);
	if (!timer || timer.intervalId) return;

	timer.paused = false;
	timer.intervalId = setInterval(() => {
		timer.timeLeft--;

		// Send updated time to all clients in room
		io.to(roomCode).emit("updateTimer", timer.timeLeft);

		// When timer reaches 0
		if (timer.timeLeft <= 0) {
			clearRoomTimer(roomCode);

			const currentPlayer = playersInRoom(roomCode).find((p) => p.socketID === timer.playerSocket);
			if (currentPlayer) {
				// Signal client to return cards
				io.to(timer.playerSocket).emit("turnTimedOut");

				// Find and give turn to next player, indicating no cards were played
				const nextPlayer = findNextTurn(timer.playerSocket, roomCode);
				handleTurnChange(roomCode, nextPlayer.socketID, currentPlayer, false);

				io.to(roomCode).emit("updateGameEventMessage", `${currentPlayer.name}'s turn timed out without playing any cards!`);
			}
		}
	}, 1000);
};

const startRoomTimer = (roomCode, currentPlayerSocket) => {
	clearRoomTimer(roomCode);
	roomTimers.set(roomCode, {intervalId: null, playerSocket: currentPlayerSocket, timeLeft: TURN_DURATION, paused: false});

	// Initialize timer for all clients
	io.to(roomCode).emit("updateTimer", TURN_DURATION);

	if (everyoneIsConnected(roomCode)) {
		runRoomTimer(roomCode);
	} else {
		roomTimers.get(roomCode).paused = true;
	}
};

const pauseRoomTimer = (roomCode) => {
	const timer = roomTimers.get(roomCode);
	if (!timer?.intervalId) return;
	clearInterval(timer.intervalId);
	timer.intervalId = null;
	timer.paused = true;
};

const resumeRoomTimer = (roomCode) => {
	const timer = roomTimers.get(roomCode);
	if (!timer || timer.intervalId || timer.timeLeft <= 0) return;
	io.to(roomCode).emit("updateTimer", timer.timeLeft);
	runRoomTimer(roomCode);
};

/* ------------------------------------------------------------------ */
/* SYSTEM CHAT MESSAGES                                                */
/* ------------------------------------------------------------------ */
const sendSystemMessage = (roomCode, message) => {
	const messageData = {
		message,
		isSystemMessage: true,
		timestamp: Date.now(),
	};
	if (!chatHistory.has(roomCode)) {
		chatHistory.set(roomCode, []);
	}
	chatHistory.get(roomCode).push(messageData);
	io.to(roomCode).emit("chatMessage", messageData);
};

/* ------------------------------------------------------------------ */
/* ROOM TEARDOWN                                                       */
/* ------------------------------------------------------------------ */
const destroyRoom = (roomCode) => {
	clearRoomTimer(roomCode);
	delete onlineUsers[roomCode];
	delete lastMovePlayedInRoom[roomCode];
	delete pileOfCardsInEachRoom[roomCode];
	roomMeta.delete(roomCode);
	chatHistory.delete(roomCode);
	console.log("Room torn down:", roomCode);
};

// Removes a player for good (as opposed to the temporary "disconnected" state).
const removePlayer = (roomCode, playerId) => {
	if (!onlineUsers[roomCode]) return;

	const wasLeader = onlineUsers[roomCode].find((player) => player.playerId === playerId)?.isLeader;
	onlineUsers[roomCode] = onlineUsers[roomCode].filter((player) => player.playerId !== playerId);
	cancelPendingRemoval(playerId);

	if (onlineUsers[roomCode].length === 0) {
		destroyRoom(roomCode);
		return;
	}

	if (wasLeader) assignNewLeader(roomCode);
	io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
};

/*
	Every id we still hold that pointed at the seat's old socket has to follow
	the chair to whoever is sitting in it now - the same player back from a
	blip, or a replacement who took it over - otherwise the game keeps talking
	to a dead socket.
*/
const rebindSeatSocket = (roomCode, previousSocketID, newSocketID) => {
	if (previousSocketID === newSocketID) return;

	const meta = getRoomMeta(roomCode);
	if (meta.currentTurnSocketID === previousSocketID) meta.currentTurnSocketID = newSocketID;
	if (meta.lastPlayedSocketID === previousSocketID) meta.lastPlayedSocketID = newSocketID;

	const timer = roomTimers.get(roomCode);
	if (timer?.playerSocket === previousSocketID) timer.playerSocket = newSocketID;

	playersInRoom(roomCode).forEach((other) => {
		if (other.preOrderInfo?.playerWhoPreordered === previousSocketID) {
			other.preOrderInfo.playerWhoPreordered = newSocketID;
		}
		if (other.issuedPreorderDetails?.playerIssuedAgainstID === previousSocketID) {
			other.issuedPreorderDetails.playerIssuedAgainstID = newSocketID;
		}
	});
};

/*
	Somebody is gone for good - they quit, or their grace window ran out. The
	table does not fold: their chair keeps its hand, its powerups and its place
	in the turn order, the clock stays stopped, and the room waits for a
	replacement to sit down.
*/
const openSeat = (roomCode, player, announcement) => {
	player.connected = false;
	player.awaitingReplacement = true;
	cancelPendingRemoval(player.playerId);
	pauseRoomTimer(roomCode);

	// Nobody is left to wait with, so there is no game left to hold open.
	if (seatedCount(roomCode) === 0) {
		playersInRoom(roomCode).forEach((seat) => cancelPendingRemoval(seat.playerId));
		destroyRoom(roomCode);
		return;
	}

	if (announcement) sendSystemMessage(roomCode, announcement);
	io.to(roomCode).emit("seatOpened", {
		playerId: player.playerId,
		name: player.name,
		openSeats: openSeatSummary(roomCode),
	});
	io.to(roomCode).emit("updateUserList", playersInRoom(roomCode));
};

/*
	Who has claimed whom. Anybody at the table may place a preorder, on their
	turn or not, so every client has to see which targets are already spoken for
	and whether their own single claim is still in hand. The roster that carries
	this also carries everybody's cards, so only the claims themselves go out.
*/
const preorderSummary = (roomCode) =>
	playersInRoom(roomCode).map((player) => ({
		socketID: player.socketID,
		isPreordered: Boolean(player.preOrderInfo?.isPreordered),
		playerWhoPreordered: player.preOrderInfo?.playerWhoPreordered ?? null,
		hasIssuedPreorder: Boolean(player.issuedPreorderDetails?.hasIssuedPreorder),
	}));

const broadcastPreorders = (roomCode) => io.to(roomCode).emit("preordersUpdated", preorderSummary(roomCode));

// Modify handleTurnChange function to include a hasPlayedCards parameter
const handleTurnChange = (roomCode, nextPlayerSocket, currentPlayer, hasPlayedCards = true) => {
	const meta = getRoomMeta(roomCode);
	const lastPlayedPlayer = hasPlayedCards ? currentPlayer?.socketID ?? null : null;

	meta.currentTurnSocketID = nextPlayerSocket;
	meta.isNewTurn = nextPlayerSocket === currentPlayer?.socketID ? false : true;
	meta.lastPlayedSocketID = lastPlayedPlayer;

	// Keep hasTurn in sync - server side checks (the skip powerup) rely on it.
	playersInRoom(roomCode).forEach((player) => {
		player.hasTurn = player.socketID === nextPlayerSocket;
	});

	// Update turn
	io.to(roomCode).emit("updateTurn", {
		currentPlayer: nextPlayerSocket,
		lastPlayedPlayer, // Only set lastPlayedPlayer if cards were played
		currentCardValue: meta.currentCardValue,
		newTurnStatus: meta.isNewTurn,
	});

	// Start new timer for next player
	startRoomTimer(roomCode, nextPlayerSocket);
};

io.on("connection", (socket) => {
	// Anything that could move the game forward asks this first: while a chair
	// is empty the round is frozen, not merely un-timed.
	const rejectWhilePaused = (roomCode) => {
		if (!roomIsPaused(roomCode)) return false;
		socket.emit("updateGameEventMessage", "The game is paused until the open seat is taken.");
		return true;
	};

	socket.on("joinRoom", (dataArray) => {
		/*	in data array 
			dataArray[0] = roomCode
			dataArray[1] = socket.id
			dataArray[2] = playerNewObj { playerId, name, avatar, isLeader, preorderEnabled }
		*/
		const [roomCode, socketID, playerInfo] = dataArray ?? [];
		if (!roomCode || !playerInfo) return;

		const meta = getRoomMeta(roomCode);
		if (!onlineUsers[roomCode]) {
			onlineUsers[roomCode] = []; // Initialize the room array if it doesn't exist
		}

		const playerId = playerInfo.playerId || randomUUID();

		/*
			The waiting area re-emits joinRoom whenever its player state changes,
			so this handler has to be idempotent. Matching on playerId (instead of
			the socket id, which changes on every reconnect) is what stops the same
			person being seated twice.
		*/
		const seated = onlineUsers[roomCode].find((player) => player.playerId === playerId);
		if (seated) {
			const previousSocketID = seated.socketID;
			const reclaimsOwnSeat = Boolean(seated.awaitingReplacement);

			seated.socketID = socketID;
			seated.connected = true;
			delete seated.disconnectedAt;
			cancelPendingRemoval(playerId);
			socket.join(roomCode);

			// They walked away from a game in progress and came back to the same
			// room code: the chair being held open is theirs to take back.
			if (reclaimsOwnSeat) {
				delete seated.awaitingReplacement;
				seated.pendingHandover = true;
				rebindSeatSocket(roomCode, previousSocketID, socketID);
				sendSystemMessage(roomCode, `${seated.name} came back and sat down again.`);
				io.to(roomCode).emit("seatFilled", {
					playerId,
					name: seated.name,
					openSeats: openSeatSummary(roomCode),
				});
				socket.emit("joinedGameInProgress", {roomCode});
			}

			io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
			return;
		}

		if (meta.gameStarted) {
			const vacantSeat = openSeatsInRoom(roomCode)[0];
			if (!vacantSeat) {
				socket.emit("joinRoomFailed", {reason: "in-progress", message: "That game has already started."});
				return;
			}

			/*
				A chair somebody walked away from is handed over exactly as they
				left it - same hand, same powerups, same place in the turn order -
				so the round resumes instead of being thrown away. Only the
				identity sitting on the seat changes.
			*/
			const previousSocketID = vacantSeat.socketID;
			const previousName = vacantSeat.name;

			socket.join(roomCode);
			cancelPendingRemoval(vacantSeat.playerId);

			Object.assign(vacantSeat, {
				playerId,
				socketID,
				name: playerInfo.name,
				avatar: playerInfo.avatar,
				connected: true,
				// attemptReconnect - which is how this client asks for the board
				// once it lands in the game room - reads this to tell a handover
				// apart from the harmless resync every client sends on connect.
				pendingHandover: true,
			});
			delete vacantSeat.awaitingReplacement;
			delete vacantSeat.disconnectedAt;

			rebindSeatSocket(roomCode, previousSocketID, socketID);

			console.log(`${vacantSeat.name} took over ${previousName}'s seat in room :`, roomCode);
			sendSystemMessage(roomCode, `${vacantSeat.name} took over ${previousName}'s seat.`);
			io.to(roomCode).emit("seatFilled", {
				playerId,
				name: vacantSeat.name,
				replacedName: previousName,
				openSeats: openSeatSummary(roomCode),
			});
			io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
			socket.emit("joinedGameInProgress", {roomCode});
			return;
		}

		if (onlineUsers[roomCode].length >= MAX_PLAYERS_PER_ROOM) {
			socket.emit("joinRoomFailed", {reason: "full", message: "That room is already full."});
			return;
		}

		socket.join(roomCode);
		console.log("Socket with ID :", socketID, "has joined room :", roomCode);

		// Drop any stale entry still holding this socket id (same tab, new identity)
		onlineUsers[roomCode] = onlineUsers[roomCode].filter((player) => player.socketID !== socketID);

		const newPlayer = {
			playerId,
			socketID,
			room: roomCode,
			name: playerInfo.name,
			avatar: playerInfo.avatar,
			isLeader: playerInfo.isLeader,
			preorderEnabled: playerInfo.preorderEnabled,
			connected: true,
		};
		onlineUsers[roomCode].push(newPlayer);

		// Check and assign leader if needed
		if (!onlineUsers[roomCode].some((player) => player.isLeader)) {
			assignNewLeader(roomCode);
		}

		// Notify all users in the room of the updated user list
		io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
		// Also send the roster directly to the joining socket so it cannot miss
		// the room update while the waiting area is mounting.
		socket.emit("updateUserList", onlineUsers[roomCode]);
	});

	/*
		Quick match: walk the open lobbies and take the first one with a free
		seat, so the oldest half-full table fills up instead of every player
		scattering into a new room of their own.
	*/
	socket.on("joinRandomRoom", () => {
		/*
			Only ever matches into rooms real players are already sitting in.
			Nothing is invented here: no placeholder room is created and no bot
			is seated. An empty result means "go create one", which is what the
			client is told.
			roomMeta is read with .get() rather than getRoomMeta() so scanning
			cannot leave phantom room records behind.
		*/
		const roomCode = Object.keys(onlineUsers).find((code) => {
			const seated = seatedCount(code);
			if (seated === 0) return false;
			// A game already running still has room if somebody vacated a chair -
			// that table is waiting for exactly this player.
			if (roomMeta.get(code)?.gameStarted) return openSeatsInRoom(code).length > 0;
			return seated < MAX_PLAYERS_PER_ROOM;
		});

		if (!roomCode) {
			socket.emit("joinRandomRoomR", {found: false});
			return;
		}

		const playersSeated = seatedCount(roomCode);
		const inProgress = Boolean(roomMeta.get(roomCode)?.gameStarted);
		console.log("Quick match sending a player to room:", roomCode, `(${playersSeated}/${MAX_PLAYERS_PER_ROOM} seated${inProgress ? ", game in progress" : ""})`);
		socket.emit("joinRandomRoomR", {found: true, roomCode, playersSeated, inProgress});
	});

	socket.on("getUsersInRoom", (roomCode) => {
		console.log("received getUsersInRoom signal from client with roomCode : ", roomCode);
		socket.emit("getUsersInRoomR", onlineUsers[roomCode] ?? []);
	});

	socket.on("navigateToGameRoom", (roomCode) => {
		io.to(roomCode).emit("navigateToGameRoomR", roomCode);
	});
	socket.on("getRoomSize", (roomCode) => {
		console.log("Room/Size : ", roomCode, onlineUsers[roomCode]?.length);
		// A room mid game reads as full by headcount even while a chair stands
		// empty, so it is the free-seat count - not the size - that decides a join.
		// Only the socket that asked - io.emit told every connected client.
		socket.emit("getRoomSizeR", {
			// "Nobody is sitting here" and "there is no such table" look identical
			// by seat count - both have room - so the answer has to say which it
			// is, or a mistyped code quietly opens a new room instead of joining.
			exists: playersInRoom(roomCode).length > 0,
			size: playersInRoom(roomCode).length,
			openSeats: freeSeatCount(roomCode),
			inProgress: Boolean(roomMeta.get(roomCode)?.gameStarted),
		});
	});

	/* START GAME LOGIC */
	socket.on("startGame", ({roomCode, socketID}) => {
		console.log("startGame signal received from client with roomCode:", roomCode);

		// Get all players in the room
		const players = onlineUsers[roomCode];
		if (!players || players.length !== MAX_PLAYERS_PER_ROOM || !everyoneIsConnected(roomCode)) {
			console.log("Need exactly 4 connected players to start the game");
			return;
		}

		// Closes the room to newcomers and to quick match
		getRoomMeta(roomCode).gameStarted = true;

		// Reset game state for the room
		pileOfCardsInEachRoom[roomCode] = [];
		lastMovePlayedInRoom[roomCode] = null;
		getRoomMeta(roomCode).currentCardValue = null;

		// Clear any existing timers
		clearRoomTimer(roomCode);

		// Create and shuffle the deck
		const deck = shuffleDeck(createDeck());

		// Deal 13 cards to each player and reset their game state
		let localPlayer;
		players.forEach((player, index) => {
			const playerCards = deck.slice(index * 13, (index + 1) * 13);

			// Update player object with fresh game state
			Object.assign(player, {
				cards: playerCards,
				preOrderInfo: {isPreordered: false, playerWhoPreordered: null},
				issuedPreorderDetails: {hasIssuedPreorder: false, playerIssuedAgainstID: null},
				score: 0,
				powerups: {0: 0, 1: 0, 2: 0},
				hasTurn: player.isLeader,
				isShielded: false,
			});

			// Store reference to leader
			if (player.socketID === socketID) {
				localPlayer = player;
			}

			// Send updated player state to EACH player individually
			io.to(player.socketID).emit("receiveCards", player);
			io.to(player.socketID).emit("updateLocalPlayer", player);
		});

		// Update global state
		onlineUsers[roomCode] = players;

		// Initialize turn for leader
		handleTurnChange(roomCode, localPlayer.socketID, null);

		// Broadcast game start to all players
		broadcastPreorders(roomCode);
		io.to(roomCode).emit("startGameR", roomCode);
		io.to(roomCode).emit("updateGameEventMessage", "New game started! Good luck!");
		io.to(roomCode).emit("updateUserList", players);
	});

	//implement server response to the player making a move
	//THE SERVER SHOULD AT ALL TIMES HAVE THE STATE OF THE GAME STORED INSIDE IT
	//WHEN A PLAYERS SENDS A makeMove signal THE SERVER WILL MAKE THE NECESSAY ADJUSTMENTS TO THE GAME STATE
	//THEN UPDATE THE STATE INTERNALLY ,CHECK FOR WINNERS,THEN PASS THE TURN TO THE NEXT PLAYER
	const checkWinner = (roomCode) => {
		const winnerPlayerObject = onlineUsers[roomCode]?.find((player) => player.cards.length === 0);
		const winnerBOOL = winnerPlayerObject !== undefined;
		console.log("winner : ", winnerPlayerObject, " winnerBool :", winnerBOOL);
		return {winnerBOOL, winnerPlayerObject: winnerBOOL ? winnerPlayerObject : null};
	};

	// Modify makeMove handler where turn changes occur
	socket.on("makeMove", ({roomCode, socketID, cardsPlayedArray, cardValueTold, isNewTurn, isFinalCard}) => {
		try {
			if (rejectWhilePaused(roomCode)) return;

			// Find the current player
			const currentPlayer = onlineUsers[roomCode]?.find((player) => player.socketID === socketID);
			console.log("\n******cardvalueTold : ", cardValueTold);
			currentPlayer.cards = currentPlayer.cards.filter((card) => !cardsPlayedArray.includes(card));

			if (!isNewTurn) {
				cardValueTold = lastMovePlayedInRoom[roomCode].cardValueTold;
			}
			getRoomMeta(roomCode).currentCardValue = cardValueTold;

			if (isFinalCard) {
				const finalCard = cardsPlayedArray[0];
				onlineUsers[roomCode]?.forEach((player) => {
					if (player.socketID === socketID) {
						player.cards = player.cards.filter((card) => !cardsPlayedArray.includes(card));
					}
				});
				// Send last card info to all clients
				io.to(roomCode).emit("lastCardPresented", {
					playerName: currentPlayer.name,
					card: finalCard,
					cardValueClaimed: cardValueTold,
					isFinalCard: true,
				});
				console.log("final card matches claim : ", cardMatchesClaim(finalCard, cardValueTold), " cardValueTold : ", cardValueTold);
				if (!cardMatchesClaim(finalCard, cardValueTold)) {
					// Player lied about their final card - they must take all cards
					console.log("I AM HERERERERERER LIEED");
					currentPlayer.cards = [...currentPlayer.cards, ...pileOfCardsInEachRoom[roomCode]];
					pileOfCardsInEachRoom[roomCode] = [];

					handleTurnChange(roomCode, socketID, currentPlayer);
					io.to(roomCode).emit("updateGameEventMessage", `${currentPlayer.name} lied about their final card and must take all cards from the pile then play again!`);

					io.to(currentPlayer.socketID).emit("updateLocalPlayer", currentPlayer);
					return;
				} else {
					const {winnerPlayerObject} = checkWinner(roomCode);
					if (winnerPlayerObject) {
						// Reopens the room: the leader can start another game from here.
						getRoomMeta(roomCode).gameStarted = false;
						clearRoomTimer(roomCode);
						if (roomCode in pileOfCardsInEachRoom) {
							delete pileOfCardsInEachRoom[roomCode];
						}
						if (roomCode in lastMovePlayedInRoom) {
							delete lastMovePlayedInRoom[roomCode];
						}
						const playersData = {
							winner: {
								socketID: winnerPlayerObject.socketID,
								name: winnerPlayerObject.name,
								avatar: winnerPlayerObject.avatar,
								cardsLeft: 0,
								isWinner: true,
							},
							players: onlineUsers[roomCode].map((player) => ({
								socketID: player.socketID,
								name: player.name,
								avatar: player.avatar,
								cardsLeft: player.cards.length,
								isWinner: player.socketID === winnerPlayerObject.socketID,
							})),
						};
						io.to(roomCode).emit("gameOver", playersData);
						io.to(roomCode).emit("updateTimer", 0);
						io.to(roomCode).emit("updateGameEventMessage", `${currentPlayer.name} has won the game by playing their final card truthfully!`);
					}
					return;
				}
			}

			// Normal turn logic
			//	currentPlayer.cards = currentPlayer.cards.filter((card) => !cardsPlayedArray.includes(card));

			// Check if player is trying to play all cards except one
			if (currentPlayer.cards.length === 0) {
				io.to(currentPlayer.socketID).emit("updateGameEventMessage", `${currentPlayer.name} must keep at least one card in hand!`);
				return;
			}

			console.log("makeMove signal received from client with roomCode:", roomCode, " with cardsPlayedArray : ", cardsPlayedArray, " cardValueTold : ", cardValueTold);
			onlineUsers[roomCode]?.forEach((player) => {
				//remove the cards played from the player's hand
				//todo check for preorder action before removing the cards entirely NO PLAY TURN THEN PREORDER ACTION WILL GET EXECUTED

				//remove the cards in cardsPlayedArray from the player cards value
				if (player.socketID === socketID) {
					player.cards = player.cards.filter((card) => !cardsPlayedArray.includes(card));
					console.log("player cards after removing the played cards : ", player.cards);
				}
			});
			//update last move played in room
			lastMovePlayedInRoom[roomCode] = {cardsPlayedArray, cardValueTold};

			// Initialize the pile if it doesn't exist
			if (!pileOfCardsInEachRoom[roomCode]) {
				pileOfCardsInEachRoom[roomCode] = [];
			}

			pileOfCardsInEachRoom[roomCode] = [...pileOfCardsInEachRoom[roomCode], ...cardsPlayedArray];
			// Check for winners
			const {winnerBOOL, winnerPlayerObject} = checkWinner(roomCode);
			// If there is a winner, send the winner to the client
			if (winnerBOOL) {
				getRoomMeta(roomCode).gameStarted = false;
				clearRoomTimer(roomCode);
				if (pileOfCardsInEachRoom.has(roomCode)) {
					pileOfCardsInEachRoom.delete(roomCode);
				}
				if (lastMovePlayedInRoom.has(roomCode)) {
					lastMovePlayedInRoom.delete(roomCode);
				}
				console.log("Game Over, Winner:", winner);
				io.to(roomCode).emit("updateTimer", 0);
				io.to(roomCode).emit("gameOver", {winnerID: winnerPlayerObject.socketID, allUsers: onlineUsers[roomCode]});
				io.to(roomCode).emit("updateGameEventMessage", `GAME OVER , ${winnerPlayerObject.name} WON THE GAME`);
			} else {
				//NEED TO CHECK IF ANY PLAYER HAS PREORDERED THE PLAYER WHO IS PLAYING THEIR TURN
				//IF YES THEN THE PLAYER WHO PREORDERED CAN ACCUSE THE PLAYER WHO IS PLAYING THEIR TURN
				//you are about to makeMove , after you make your move, if you are preodered,
				//the player who preordered you will see the cards you last played : cardsPlayedArray , if they are wrong , you get turn and can choose newTurnCard & they take cardPlayedArray, if they are right , they get turn and can choose newTurnCard & you take cardPlayedArray
				onlineUsers[roomCode]?.forEach((player) => {
					if (player.socketID === socketID) {
						if (player.preOrderInfo.isPreordered) {
							const accuserFromPreorderSocketID = player.preOrderInfo.playerWhoPreordered;
							io.to(accuserFromPreorderSocketID).emit("accusePlayer", {roomCode: roomCode, socketID: accuserFromPreorderSocketID, accusedPlayerID: player.socketID});
						}
					}
				});

				// Before updating turn, store the last player who made a move
				const lastPlayedPlayer = socketID;
				const nextPlayer = findNextTurn(socketID, roomCode);

				handleTurnChange(roomCode, nextPlayer.socketID, currentPlayer);

				io.to(roomCode).emit("updateGameEventMessage", `${onlineUsers[roomCode]?.find((player) => player.socketID === socketID).name} has played their turn : ${cardsPlayedArray.length} ${cardsPlayedArray.length == 1 ? "card" : "cards"} of value : ${cardValueTold}`);
			}

			// After a successful move, the next turn should be a new turn
			const nextPlayer = findNextTurn(socketID, roomCode);
			handleTurnChange(roomCode, nextPlayer.socketID, currentPlayer);

			// Reset new turn status after move is completed
			io.to(roomCode).emit("updateNewTurnStatus", false);
		} catch (error) {
			console.log("Error in makeMove:", error);
		}
	});

	// Modify accuse handler
	socket.on("accuse", ({roomCode, socketID, accusedPlayerID}) => {
		try {
			if (rejectWhilePaused(roomCode)) return;

			const accuser = onlineUsers[roomCode]?.find((player) => player.socketID === socketID);
			const accused = onlineUsers[roomCode]?.find((player) => player.socketID === accusedPlayerID);

			if (!accuser || !accused) {
				console.error("Could not find accuser or accused player");
				return;
			}
			if (getRoomMeta(roomCode).lastPlayedSocketID !== accusedPlayerID) return;

			// Emit accusation started event to all players in room
			io.to(roomCode).emit("accusationStarted", {
				accuserId: socketID,
				accusedId: accusedPlayerID,
				accuserName: accuser.name,
				accusedName: accused.name,
			});

			// Get the last move played
			const {cardsPlayedArray, cardValueTold} = lastMovePlayedInRoom[roomCode] || {};

			// Process the accusation
			const accuserIsRight = cardsPlayedArray.some((card) => !cardMatchesClaim(card, cardValueTold));

			if (accuserIsRight) {
				// Accused takes all cards
				accused.cards = [...accused.cards, ...pileOfCardsInEachRoom[roomCode]];
				pileOfCardsInEachRoom[roomCode] = [];
				//grant a powerup to the accuser
				//ONLY 3 POWERUPS FOR NOW
				const NUMBER_OF_POWERUPS = 3;
				const powerUpID = Math.floor(Math.random() * NUMBER_OF_POWERUPS);
				accuser.powerups[powerUpID] += 1;
				onlineUsers[roomCode]?.forEach((player) => {
					if (player.socketID === accuser.socketID) player = accuser;
				});
				io.to(roomCode).emit("playPowerupDice", {accuserID: socketID, accuserName: accuser.name, accusedName: accused.name, powerUpID: powerUpID});
				handleTurnChange(roomCode, socketID, accused, false);
				io.to(roomCode).emit("updateGameEventMessage", `Accuser ${accuser.name} was right, ${accused.name} takes all cards , and ${accuser.name} has TURN`);
			} else {
				// Accuser takes all cards
				accuser.cards = [...accuser.cards, ...pileOfCardsInEachRoom[roomCode]];
				pileOfCardsInEachRoom[roomCode] = [];
				// Give turn to accused
				handleTurnChange(roomCode, accusedPlayerID, accuser, false);
				onlineUsers[roomCode]?.forEach((player) => {
					if (player.socketID === accused.socketID) player = accused;
				});
				io.to(accuser.socketID).emit("updateLocalPlayer", accuser);
				io.to(roomCode).emit("updateGameEventMessage", `Accuser ${accuser.name} was wrong, ${accuser.name} takes all cards , and ${accused.name} has TURN`);
			}

			io.to(roomCode).emit("updateNewTurnStatus", true);
			getRoomMeta(roomCode).currentCardValue = null;
			//empty all preorders in the room , all preOrderInfo and issuedPreorderDetails
			//might need to refacotr the meptying of other preorders on top
			onlineUsers[roomCode].forEach((player) => {
				player.preOrderInfo = {isPreordered: false, playerWhoPreordered: null};
				player.issuedPreorderDetails = {hasIssuedPreorder: false, playerIssuedAgainstID: null};
				io.to(player.socketID).emit("updateLocalPlayer", player);
			});
			broadcastPreorders(roomCode);

			// After accusation is resolved (success or failure), emit resolution
			io.to(roomCode).emit("accusationResolved");
		} catch (error) {
			console.log("error in accuse:", error);
			// Make sure to resolve the accusation state even on error
			io.to(roomCode).emit("accusationResolved");
		}
	});

	socket.on("preorder", async ({roomCode, socketID, accusedPlayerID}) => {
		// roomCode,
		// 		socketID: localPlayerID,
		// 		accusedPlayerID: actualPlayerID,
		try {
			if (!roomCode || !socketID || !accusedPlayerID) {
				console.error("Missing required parameters for accusation:", {roomCode, socketID, accusedPlayerID});
				return;
			}
			if (rejectWhilePaused(roomCode)) return;
			// A preorder needs no turn, but it does need somebody else to aim at.
			if (socketID === accusedPlayerID) return;
			const playerToBePreordered = onlineUsers[roomCode]?.find((player) => player.socketID === accusedPlayerID);
			const playerWhoPreordered = onlineUsers[roomCode]?.find((player) => player.socketID === socketID);
			const roomHasPreorderEnabled = playerToBePreordered.preorderEnabled;

			//in case the the frontend check gets bypassed
			if (!roomHasPreorderEnabled) {
				return;
			}
			if (playerToBePreordered.preOrderInfo.isPreordered) {
				const aux = onlineUsers[roomCode]?.find((p) => p.socketID === playerToBePreordered.preOrderInfo.playerWhoPreordered);
				console.log(`player ${playerToBePreordered.socketID} is already preordered by ${aux.name} in room : ${roomCode}`);
				io.to(playerWhoPreordered.socketID).emit("updateGameEventMessage", `Player ${playerToBePreordered.name} is already preordered by ${aux.name} `);
				return;
			} else {
				if (playerWhoPreordered.issuedPreorderDetails.hasIssuedPreorder) {
					const playerIssuedAgainst = onlineUsers[roomCode]?.find((p) => p.socketID === playerWhoPreordered.issuedPreorderDetails.playerIssuedAgainstID);
					console.log(`player ${playerWhoPreordered.socketID}  has already preordered ${playerIssuedAgainst.socketID} in room : ${roomCode}`);
					io.to(playerWhoPreordered.socketID).emit("updateGameEventMessage", `Player  ${playerIssuedAgainst.name} has already issued a preorder on : ${playerToBePreordered.name}`);
					return;
				}
				playerToBePreordered.preOrderInfo = {isPreordered: true, playerWhoPreordered: playerWhoPreordered.socketID};
				playerWhoPreordered.issuedPreorderDetails = {hasIssuedPreorder: true, playerIssuedAgainstID: accusedPlayerID};
				io.to(playerWhoPreordered.socketID).emit("updateLocalPlayer", playerWhoPreordered);
				io.to(playerToBePreordered.socketID).emit("updateLocalPlayer", playerToBePreordered);
				broadcastPreorders(roomCode);
				io.to(roomCode).emit("updateGameEventMessage", `${playerToBePreordered.name} has been preordered by ${playerWhoPreordered.name}`);
				console.log(`${playerToBePreordered.name} has been preordered by ${playerWhoPreordered.name} in room ${roomCode}`);
			}
		} catch (error) {
			console.log("error in preorder : ", error, " \n");
		}
	});
	/* END GAME LOGIC */

	/* ------------------------------------------------------------------ */
	/* RECONNECTION                                                        */
	/* ------------------------------------------------------------------ */
	socket.on("attemptReconnect", ({roomCode, playerId}) => {
		try {
			console.log("Reconnect attempt for player", playerId, "in room", roomCode);

			const room = onlineUsers[roomCode];
			if (!room || room.length === 0) {
				socket.emit("reconnectionFailed", {reason: "room-gone", message: "That game no longer exists."});
				return;
			}

			const player = room.find((seatedPlayer) => seatedPlayer.playerId === playerId);
			if (!player) {
				socket.emit("reconnectionFailed", {reason: "seat-lost", message: "Your seat at that table is gone."});
				return;
			}

			const previousSocketID = player.socketID;
			const meta = getRoomMeta(roomCode);
			// Read before we flip them: socket.io's connectionStateRecovery can hand
			// back the *same* socket id, so the id alone cannot tell a real
			// reconnection from the harmless resync every client sends on connect.
			// A handover (joinRoom just sat somebody new in this chair) counts as
			// a real one too - the board has to be re-broadcast for the new id.
			const isHandover = player.pendingHandover === true;
			const reclaimedOpenSeat = player.awaitingReplacement === true;
			const wasAway = player.connected === false || isHandover;

			player.socketID = socket.id;
			player.connected = true;
			delete player.disconnectedAt;
			delete player.awaitingReplacement;
			delete player.pendingHandover;
			socket.join(roomCode);
			cancelPendingRemoval(playerId);

			// Everything that was keyed on the old socket id has to follow the player
			// to their new one, or the game would keep talking to a dead socket.
			rebindSeatSocket(roomCode, previousSocketID, socket.id);

			// Hand the returning player the whole board back. Their own hand is
			// included; everybody else's is stripped - the roster only needs
			// identity and public state to redraw the table.
			const roster = room.map(({cards, ...publicState}) => publicState);

			socket.emit("reconnectionSuccessful", {
				player,
				players: roster,
				gameStarted: meta.gameStarted,
				currentTurnSocketID: meta.currentTurnSocketID,
				lastPlayedSocketID: meta.lastPlayedSocketID,
				currentCardValue: meta.currentCardValue,
				isNewTurn: meta.isNewTurn,
				timeLeft: roomTimers.get(roomCode)?.timeLeft ?? 0,
				pileCount: (pileOfCardsInEachRoom[roomCode] ?? []).length,
				preorders: preorderSummary(roomCode),
				chatHistory: chatHistory.get(roomCode) ?? [],
			});

			// The client re-syncs on every connect, including the first one when it
			// walks in from the waiting area. That is not a reconnection, so only
			// tell the rest of the room when the player was genuinely away.
			const isRealReconnect = wasAway || previousSocketID !== socket.id;
			if (isRealReconnect) {
				io.to(roomCode).emit("playerConnectionChanged", {playerId, name: player.name, connected: true});
				io.to(roomCode).emit("updateUserList", room);
				// A handover was already announced by joinRoom, under the name of
				// whoever gave the chair up.
				if (!isHandover) sendSystemMessage(roomCode, `${player.name} reconnected.`);
			}

			// The room was waiting on this chair - tell it the wait is over.
			if (reclaimedOpenSeat) {
				io.to(roomCode).emit("seatFilled", {
					playerId,
					name: player.name,
					openSeats: openSeatSummary(roomCode),
				});
			}

			if (isRealReconnect && meta.gameStarted && everyoneIsConnected(roomCode)) {
				// Re-broadcast the turn so every other client swaps the dead socket
				// id for the new one, then let the clock run again.
				io.to(roomCode).emit("updateTurn", {
					currentPlayer: meta.currentTurnSocketID,
					lastPlayedPlayer: meta.lastPlayedSocketID,
					currentCardValue: meta.currentCardValue,
					newTurnStatus: meta.isNewTurn,
				});
				resumeRoomTimer(roomCode);
			}
		} catch (error) {
			console.error("Reconnection error:", error);
			socket.emit("reconnectionFailed", {reason: "error", message: "Something went wrong reconnecting."});
		}
	});

	/* ------------------------------------------------------------------ */
	/* DISCONNECTION                                                       */
	/* ------------------------------------------------------------------ */
	socket.on("disconnect", (reason) => {
		console.log(`Socket with ID ${socket.id} has disconnected, reason: ${reason}`);

		Object.keys(onlineUsers).forEach((roomCode) => {
			const player = playersInRoom(roomCode).find((seatedPlayer) => seatedPlayer.socketID === socket.id);
			if (!player) return;

			const meta = getRoomMeta(roomCode);

			// In the lobby there is no state worth preserving - free the seat.
			if (!meta.gameStarted) {
				removePlayer(roomCode, player.playerId);
				return;
			}

			// Mid game the seat (and the hand that goes with it) is held open.
			player.connected = false;
			player.disconnectedAt = Date.now();
			pauseRoomTimer(roomCode);

			io.to(roomCode).emit("playerConnectionChanged", {
				playerId: player.playerId,
				name: player.name,
				connected: false,
				graceSeconds: RECONNECT_GRACE_SECONDS,
			});
			io.to(roomCode).emit("updateUserList", onlineUsers[roomCode]);
			sendSystemMessage(roomCode, `${player.name} lost connection. Holding their seat for ${RECONNECT_GRACE_SECONDS}s…`);

			cancelPendingRemoval(player.playerId);
			pendingRemovals.set(
				player.playerId,
				setTimeout(() => {
					pendingRemovals.delete(player.playerId);

					const stillMissing = playersInRoom(roomCode).find((seatedPlayer) => seatedPlayer.playerId === player.playerId && seatedPlayer.connected === false);
					if (!stillMissing) return; // they made it back in time

					// Four players are required, so rather than throwing the round
					// away the chair is held open - with the hand still on it - for
					// whoever sits down next, the original player included.
					openSeat(roomCode, stillMissing, `${player.name} did not come back. Their seat is open - share the code ${roomCode} and the game picks up where it stopped.`);
				}, RECONNECT_GRACE_SECONDS * 1000)
			);
		});
	});

	// Add handler for manual quit
	socket.on("leaveRoom", (roomCode) => {
		socket.leave(roomCode);

		const leavingPlayer = playersInRoom(roomCode).find((user) => user.socketID === socket.id);
		if (!leavingPlayer) return;

		const meta = getRoomMeta(roomCode);

		// Quitting is deliberate, so there is no grace period to wait out - but
		// the chair (and the hand on it) still stays at the table for whoever
		// takes it next. Only an unstarted lobby frees a seat outright.
		if (meta.gameStarted) {
			openSeat(roomCode, leavingPlayer, `${leavingPlayer.name} left the table. Their seat is open - share the code ${roomCode} to fill it.`);
			return;
		}

		removePlayer(roomCode, leavingPlayer.playerId);
	});

	socket.on("usePowerup", ({type, powerupId, roomCode, userId, targetId}) => {
		if (rejectWhilePaused(roomCode)) return;

		const player = onlineUsers[roomCode]?.find((p) => p.socketID === userId);
		const targetPlayer = onlineUsers[roomCode]?.find((p) => p.socketID === targetId);

		if (!player || player.powerups[powerupId] <= 0) {
			return;
		}

		// Nothing to cleanse means nothing to spend a cleanse on.
		if (type === "cleanse" && !player.preOrderInfo?.isPreordered) {
			io.to(userId).emit("updateGameEventMessage", "Nobody has preordered you — there is nothing to cleanse.");
			return;
		}

		// Reduce powerup count
		player.powerups[powerupId]--;

		// Notify client about powerup consumption
		io.to(userId).emit("powerupUsed", {type, powerupId});

		switch (type) {
			case "trueVision":
				if (targetPlayer) {
					// Send cards only to the player who used the powerup
					//don't send all cards , rather send a precentage of the cards
					const PERCENTAGE_OF_CARDS_TO_SEE = 0.3;
					const cardsToSend = Math.max(Math.floor(targetPlayer.cards.length * PERCENTAGE_OF_CARDS_TO_SEE), 1);
					io.to(userId).emit("revealCards", {
						cards: targetPlayer.cards.slice(0, cardsToSend),
						playerName: targetPlayer.name,
					});
					console.log("True Vision used on:", targetPlayer.name);
					// Notify room about powerup use
					io.to(roomCode).emit("updateGameEventMessage", `${player.name} used True Vision on ${targetPlayer.name}!`);
				}
				break;

			case "skipPlayer":
				const currentTurnPlayer = onlineUsers[roomCode].find((p) => p.hasTurn)?.socketID;
				if (targetPlayer && targetPlayer.socketID === currentTurnPlayer) {
					const nextPlayer = findNextTurn(targetId, roomCode);
					handleTurnChange(roomCode, nextPlayer.socketID, targetPlayer, false);

					// Decrement powerup count since it was used successfully
					player.powerups[powerupId]--;
					io.to(roomCode).emit("updateGameEventMessage", `${player.name} skipped ${targetPlayer.name}'s turn!`);

					// Notify about powerup usage
					io.to(userId).emit("powerupUsed", {type: "skipPlayer", powerupId});
				} else {
					// Send error message only to the player who tried to use the powerup
					io.to(userId).emit("updateGameEventMessage", `Can't skip ${targetPlayer.name}'s turn as they don't have the current turn!`);
				}
				break;

			case "cleanse": {
				// The claim is off this player - and the one claim its owner was
				// allowed goes back to them, or they could never preorder again.
				const meta = getRoomMeta(roomCode);
				const claimOwner = onlineUsers[roomCode]?.find((p) => p.socketID === player.preOrderInfo?.playerWhoPreordered);
				player.preOrderInfo = {isPreordered: false, playerWhoPreordered: null};
				if (meta.lastPlayedSocketID === player.socketID) {
					meta.lastPlayedSocketID = null;
					io.to(roomCode).emit("updateTurn", {
						currentPlayer: meta.currentTurnSocketID,
						lastPlayedPlayer: null,
						currentCardValue: meta.currentCardValue,
						newTurnStatus: meta.isNewTurn,
					});
				}
				if (claimOwner) {
					claimOwner.issuedPreorderDetails = {hasIssuedPreorder: false, playerIssuedAgainstID: null};
					io.to(claimOwner.socketID).emit("updateLocalPlayer", claimOwner);
				}
				io.to(userId).emit("updateLocalPlayer", player);
				broadcastPreorders(roomCode);
				io.to(roomCode).emit("updateGameEventMessage", `${player.name} cleansed all preorders!`);
				break;
			}
		}

		// Update powerup state for user
		io.to(userId).emit("updateLocalPlayer", player);
	});

	// Server-side code
	socket.on("globalAccusation", ({roomCode, accusedPlayerID}) => {
		// Broadcast to all clients in the room that this player has been accused
		io.to(roomCode).emit("playerAccused", {
			accusedId: accusedPlayerID,
			accused: true,
		});
	});

	socket.on("sendMessage", ({roomCode, message, playerName}) => {
		const messageData = {
			playerName,
			message,
			timestamp: Date.now(),
		};

		// Store message in history
		if (!chatHistory.has(roomCode)) {
			chatHistory.set(roomCode, []);
		}
		chatHistory.get(roomCode).push(messageData);

		// Keep only last 50 messages
		if (chatHistory.get(roomCode).length > 50) {
			chatHistory.get(roomCode).shift();
		}

		// Broadcast to room
		io.to(roomCode).emit("chatMessage", messageData);
	});

	socket.on("getChatHistory", (roomCode) => {
		const history = chatHistory.get(roomCode) || [];
		socket.emit("chatHistory", history);
	});

	socket.on("startGame", ({roomCode}) => {
		sendSystemMessage(roomCode, "Game has started!");
	});

	socket.on("makeMove", ({roomCode, socketID}) => {
		const player = onlineUsers[roomCode]?.find((u) => u.socketID === socketID);
		if (player) sendSystemMessage(roomCode, `${player.name} played their cards.`);
	});

});

//I NEED TO SEND A SIGNAL TO THE SERVER WHEN THE BUTTON TURNS GREEN LETTING THE SERVER KNOW TO SEND AN EVENT TO ALL IN THE ROOM TO TELL THEM TO NAVIGATE TO THE GAMEROOM

// io.listen(port, () => {
// 	console.log(`Server running on port ${port}`);
// });

/* ************************** */
/* *****	MIDDLEWARE	***** */
/* ************************** */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
app.use(express.static(path.join(__dirname, "public"))); // Serve static files from the public directory

app.use(express.json());
app.use("/api/players", playerRouter);
app.use("/api/gameState", gameStateRouter);
app.use("/api/gameRoom", gameRoomRouter);
app.use("/api/gameConfig", gameConfigurationRouter);
/* ******* END MIDDLEWARE ******* */

/* ************************** */
/* ****	  DB CONNECTION	 **** */
/* ************************** */
mongoose
	.connect(uri)
	.then(() => console.log("MongoDB connection established!"))
	.catch((error) => console.log("MongoDB connection failed,", error.message));
//TODO THE ROOMCODE SHOWS UP WHEN I PRESS CTRL+S ON THE SERVER WTF
//MAKE SURE THE SOCKET HANDLING IS GLOBAL ON CLIENT SIDE
//LOOK IN TO CHAT APP CHATCONTEXT FILE FOR GUIDANCE
// you can use express-session to automatically create a persistent session for each new user and you can even store data in that session object that will be available on each page the user requests.

//TODO IF THE LEADER DISCONNECTS ASSIGN A NEW ONE TO THE ROOM STILL NOT DONE
//IF GAME ROOM RELOADS A PLAYER GETS DISCONNECTED

//TODO REFACTOR THE ONLINEUSERS ARRAY INTO A MAP FOR BETTER PERFORMANCE IF THE GAME GROWS PORT
//MIGHT NEED TO REWRITE THE WHOLE INDEX.JS SERVER CODE

/*

TOMORROW
MAKE SURE THAT A PLAYER CANNOT PLAY ALL HIS HAND IN ONE GO AND WIN AUTO
A PLAYER CAN PLAY ALL HIS CARDS EXCEPT HE HAS TO KEEP ONE IN HAND TO NOT WIN AUTO
AND ONLY WHEN HE HAS ONLY ONE CARD LEFT THEN HE CAN PLAY IT FACE UP AND WIN ,
IF HE PLAYS THE LAST CARD FACE UP AND IT IS NOT THE SAME AS THE CARD VALUE TOLD THEN HE HAS TO TAKE THE WHOLE PILE OF CARDS TO HIS HAND ELSE HE WINS
DONE EXCEPT FOR THE LAST CARD BEING FACE UP 

TODO IMPLEMENT THE TIMER LOGIC WHEN STARTING A TURN AND STUFF DONE
TODO IMPLEMENT THE CHATBOX  DONE 
TODO IMLEMENT THE POWERUPS LOGIC , SHIELD TO PROTECT AGAINST AN ACCUSE ,MAKE A PLAYER SKIP THEIR TURN ,TRUE VISION TO SELECT A PLAYERS HAND TO SEE IT , CLEANSE REMOVES YOUR PREORDER FOR THE TURN
WHEN A PLAYER ACCUSES SOMEONE AND IS RIGHT ,  A DICE ROLLS AND THE ACCUSER GETS A RANDOM POWERUP DONE
*/

/*
TOMORROW : TODO : IMPLEMENT THE RECONNECTION LOGIC FOR THE SOCKETS
TODO : ADD SOUND EFFECTS TO THE GAME
TODO : IMPLEMENT SETTINGS ON THE CLIENT SIDE TO ALLOW THE PLAYER TO CHANGE THEME , SOUNDS , ETC 
TODO : IMPLEMENT CONTACT US FORM WITH MY EMAIL ADDRESS FOR FEEDBACK
TODO : IMPLEMENT HOW TO PLAY TUTORIAL
TODO : FINALLY FIX THE UI AND IMPROVE IT
*/
